Add COSMIC Protocols
vially/wayland-explorer pull request #77
Opened 2024-08-25 11:17 UTC by bbb651

Adds the [cosmic protocols](https://github.com/pop-os/cosmic-protocols) (still missing the compositor support info). I'm not sure about the order it should appear in, I placed it after everything else but weston and external.
I'm also not sure about the badge colors, I couldn't get a light background and dark text to work as it didn't look like the cosmic orange accent color and was too close to in appearance to weston, so I used the accent color as the background.
I ran into [this](https://github.com/facebook/create-react-app/issues/12409) while debugging which made it really annoying to test, did you also ran into this issue?

2024-08-25 14:25 UTC, vially requested changes
Looks great, thanks a lot for the contribution. The `eslint-disable-next-line` comment is required to fix the CI pipeline. Once that's fixed i'll approve and merge it.

2024-08-25 14:25 UTC, vially commented on src/components/content/ProtocolBadge.tsx
> +    backgroundColor: 'bg-orange-400',
I find the contrast between these two colors a bit hard-to-read:

![20240825_15h20m44s_grim](https://github.com/user-attachments/assets/5bf28c51-bfbc-4730-8522-43bb33a4f3c7)

I see what you mean about being difficult to find some colors that match the COSMIC logo though. I've tried a few combinations and the best options I could find are either `amber` or `yellow` (for both text and background).

### yellow

```yaml
textColor: 'text-yellow-100'
backgroundColor: 'bg-yellow-800'
```

![20240825_15h09m51s_grim](https://github.com/user-attachments/assets/a6f08006-0d25-4323-8f97-c435002f305a)

### amber

```yaml
textColor: 'text-amber-100'
backgroundColor: 'bg-amber-800'
```

![20240825_15h10m35s_grim](https://github.com/user-attachments/assets/9023de33-8e24-43fb-b3da-c1cb17546998)

Neither of them is great, but for these two options the contrast seems to be slightly better.  I don't have strong opinions on it though so I'm fine with either one of these 3 options in the end.

2024-08-25 14:48 UTC, bbb651 commented
You are right about the contrast, I forgot to check it and it's really low:
![image](https://github.com/user-attachments/assets/baa313d4-8148-4ae2-8611-cf5461429ab8)
I also tried pure white text and it's not much better:
![image](https://github.com/user-attachments/assets/fa7fd538-50ce-455f-9ff3-3d511817dfee)
Your suggestions:
- Normal:
![image](https://github.com/user-attachments/assets/ccc26947-6211-4298-a867-a956a5e0b11e)
![image](https://github.com/user-attachments/assets/7b40685f-6121-4df6-86d6-9f2fd4f824be)

- With white text instead:
![image](https://github.com/user-attachments/assets/5ccd9b3a-6352-4491-9c60-6c786ad16283)
![image](https://github.com/user-attachments/assets/64820e90-671d-4793-9182-2fd90e8a649e)

I don't have a strong opinion about it either and my display has terrible color accuracy. Maybe it's better to just go for a light background if the color can't be close enough to the right one. I'll ask in the PopOS Mattermost if they have a preference.

(The app I used is [Contrast](https://flathub.org/apps/org.gnome.design.Contrast))

2024-08-26 16:25 UTC, bbb651 commented
They did not answer so I assume it's not that important, I was probably overthinking it. I switched it to a light background to be more consistent with the other badges, and it still looks orange and is distinguishable enough from weston (at least for me), and has good enough contrast. 
![image](https://github.com/user-attachments/assets/2f3143d4-7d30-4e88-ae09-34cada591dc2)

2024-08-26 17:41 UTC, vially approved these changes
Looks great, thanks for your contribution! :tada:

2024-08-26 17:41 UTC, merged

2024-08-26 17:52 UTC, bbb651 commented
Thanks! You can close #67. Also I just made one for compositor support data #78